# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/emmanuel/workdirectory/SimTENIS

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/emmanuel/workdirectory/SimTENIS/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emmanuel/workdirectory/SimTENIS/build/CMakeFiles /home/emmanuel/workdirectory/SimTENIS/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/emmanuel/workdirectory/SimTENIS/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exeTENIS

# Build rule for target.
exeTENIS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exeTENIS
.PHONY : exeTENIS

# fast build rule for target.
exeTENIS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/build
.PHONY : exeTENIS/fast

#=============================================================================
# Target rules for targets named simTENIS

# Build rule for target.
simTENIS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simTENIS
.PHONY : simTENIS

# fast build rule for target.
simTENIS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simTENIS.dir/build.make CMakeFiles/simTENIS.dir/build
.PHONY : simTENIS/fast

TENISDetectorConstruction.o: TENISDetectorConstruction.cc.o
.PHONY : TENISDetectorConstruction.o

# target to build an object file
TENISDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISDetectorConstruction.cc.o
.PHONY : TENISDetectorConstruction.cc.o

TENISDetectorConstruction.i: TENISDetectorConstruction.cc.i
.PHONY : TENISDetectorConstruction.i

# target to preprocess a source file
TENISDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISDetectorConstruction.cc.i
.PHONY : TENISDetectorConstruction.cc.i

TENISDetectorConstruction.s: TENISDetectorConstruction.cc.s
.PHONY : TENISDetectorConstruction.s

# target to generate assembly for a file
TENISDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISDetectorConstruction.cc.s
.PHONY : TENISDetectorConstruction.cc.s

TENISEvent.o: TENISEvent.cc.o
.PHONY : TENISEvent.o

# target to build an object file
TENISEvent.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISEvent.cc.o
.PHONY : TENISEvent.cc.o

TENISEvent.i: TENISEvent.cc.i
.PHONY : TENISEvent.i

# target to preprocess a source file
TENISEvent.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISEvent.cc.i
.PHONY : TENISEvent.cc.i

TENISEvent.s: TENISEvent.cc.s
.PHONY : TENISEvent.s

# target to generate assembly for a file
TENISEvent.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISEvent.cc.s
.PHONY : TENISEvent.cc.s

TENISMaterials.o: TENISMaterials.cc.o
.PHONY : TENISMaterials.o

# target to build an object file
TENISMaterials.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISMaterials.cc.o
.PHONY : TENISMaterials.cc.o

TENISMaterials.i: TENISMaterials.cc.i
.PHONY : TENISMaterials.i

# target to preprocess a source file
TENISMaterials.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISMaterials.cc.i
.PHONY : TENISMaterials.cc.i

TENISMaterials.s: TENISMaterials.cc.s
.PHONY : TENISMaterials.s

# target to generate assembly for a file
TENISMaterials.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISMaterials.cc.s
.PHONY : TENISMaterials.cc.s

TENISSteppingAction.o: TENISSteppingAction.cc.o
.PHONY : TENISSteppingAction.o

# target to build an object file
TENISSteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISSteppingAction.cc.o
.PHONY : TENISSteppingAction.cc.o

TENISSteppingAction.i: TENISSteppingAction.cc.i
.PHONY : TENISSteppingAction.i

# target to preprocess a source file
TENISSteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISSteppingAction.cc.i
.PHONY : TENISSteppingAction.cc.i

TENISSteppingAction.s: TENISSteppingAction.cc.s
.PHONY : TENISSteppingAction.s

# target to generate assembly for a file
TENISSteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISSteppingAction.cc.s
.PHONY : TENISSteppingAction.cc.s

TENISaction.o: TENISaction.cc.o
.PHONY : TENISaction.o

# target to build an object file
TENISaction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISaction.cc.o
.PHONY : TENISaction.cc.o

TENISaction.i: TENISaction.cc.i
.PHONY : TENISaction.i

# target to preprocess a source file
TENISaction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISaction.cc.i
.PHONY : TENISaction.cc.i

TENISaction.s: TENISaction.cc.s
.PHONY : TENISaction.s

# target to generate assembly for a file
TENISaction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISaction.cc.s
.PHONY : TENISaction.cc.s

TENISgenerator.o: TENISgenerator.cc.o
.PHONY : TENISgenerator.o

# target to build an object file
TENISgenerator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISgenerator.cc.o
.PHONY : TENISgenerator.cc.o

TENISgenerator.i: TENISgenerator.cc.i
.PHONY : TENISgenerator.i

# target to preprocess a source file
TENISgenerator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISgenerator.cc.i
.PHONY : TENISgenerator.cc.i

TENISgenerator.s: TENISgenerator.cc.s
.PHONY : TENISgenerator.s

# target to generate assembly for a file
TENISgenerator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISgenerator.cc.s
.PHONY : TENISgenerator.cc.s

TENISphys.o: TENISphys.cc.o
.PHONY : TENISphys.o

# target to build an object file
TENISphys.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISphys.cc.o
.PHONY : TENISphys.cc.o

TENISphys.i: TENISphys.cc.i
.PHONY : TENISphys.i

# target to preprocess a source file
TENISphys.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISphys.cc.i
.PHONY : TENISphys.cc.i

TENISphys.s: TENISphys.cc.s
.PHONY : TENISphys.s

# target to generate assembly for a file
TENISphys.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/TENISphys.cc.s
.PHONY : TENISphys.cc.s

run.o: run.cc.o
.PHONY : run.o

# target to build an object file
run.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/run.cc.o
.PHONY : run.cc.o

run.i: run.cc.i
.PHONY : run.i

# target to preprocess a source file
run.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/run.cc.i
.PHONY : run.cc.i

run.s: run.cc.s
.PHONY : run.s

# target to generate assembly for a file
run.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/run.cc.s
.PHONY : run.cc.s

tenis.o: tenis.cc.o
.PHONY : tenis.o

# target to build an object file
tenis.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/tenis.cc.o
.PHONY : tenis.cc.o

tenis.i: tenis.cc.i
.PHONY : tenis.i

# target to preprocess a source file
tenis.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/tenis.cc.i
.PHONY : tenis.cc.i

tenis.s: tenis.cc.s
.PHONY : tenis.s

# target to generate assembly for a file
tenis.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exeTENIS.dir/build.make CMakeFiles/exeTENIS.dir/tenis.cc.s
.PHONY : tenis.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simTENIS"
	@echo "... exeTENIS"
	@echo "... TENISDetectorConstruction.o"
	@echo "... TENISDetectorConstruction.i"
	@echo "... TENISDetectorConstruction.s"
	@echo "... TENISEvent.o"
	@echo "... TENISEvent.i"
	@echo "... TENISEvent.s"
	@echo "... TENISMaterials.o"
	@echo "... TENISMaterials.i"
	@echo "... TENISMaterials.s"
	@echo "... TENISSteppingAction.o"
	@echo "... TENISSteppingAction.i"
	@echo "... TENISSteppingAction.s"
	@echo "... TENISaction.o"
	@echo "... TENISaction.i"
	@echo "... TENISaction.s"
	@echo "... TENISgenerator.o"
	@echo "... TENISgenerator.i"
	@echo "... TENISgenerator.s"
	@echo "... TENISphys.o"
	@echo "... TENISphys.i"
	@echo "... TENISphys.s"
	@echo "... run.o"
	@echo "... run.i"
	@echo "... run.s"
	@echo "... tenis.o"
	@echo "... tenis.i"
	@echo "... tenis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

